### ISSUE TITLE
Need help with an Account, should be a quick tweak

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#119]
So we're talking to a potential major client, he lost/forgot his password, here's the account details:

- brian@emmllc.com
- First and last name: Brian Samuels

If you can, let's change the password to; 123123123123

**Comment by pellarboss** [comment]
@toomingos 
is it possible to get the user to use "Forgot password" work flow?

**Comment by toomingos** [comment]
We tried to reset it for him and he can’t login, so we want to make this easy as possible for him if that's ok. He is a big potential client after all.

Thank you for help Roy!

**Comment by pellarboss** [comment]
password reset complete

**Comment by pellarboss** [comment]
from logs:
https://admin.curate.style/users/10c8aab4efb47d310f4b49e1c7fb377301ec

we saw the user hasn't clicked on "Forgot Password" since July 1st

to do this for a user, you can:
- click on "forgot password" in app
- navigate to the user in admin
- use the code to reset the password

Be aware this is SUPER unsecure, we do not recommend doing this. since we are sharing password over plain text over communication channels

please chat with me on slack
@toomingos

**Comment by toomingos** [comment]
thanks!

**Comment by toomingos** [comment]
Cant find you on Slack? my email on it is toomingos@gmail.com, name: Tomás Domingos

**Comment by toomingos** [comment]
Joe seems to have logged in the account so I think we're good to go, also, the slack invite you sent was for a paid thing so I didnt accept it. Sorry about that
