### ISSUE TITLE
[External] - Trustee Wallet

### ISSUE THREAD

**Issue by pellarboss** [pellartech/curate#126]
can you help with getting out logo on trustwallet? We've paid the BNB fee and have a pull request on their GIT: https://github.com/trustwallet/assets

trustwallet/assets
A comprehensive, up-to-date collection of information about several thousands (!) of crypto tokens.
Website
https://developer.trustwallet.com/add_new_asset

**Comment by pellarboss** [comment]
@curateproject  - what exactly would you like assistance on?  

Which of the following are done? Please tick, if you already have a PR, please provide access 

- [ ]  Make sure your smartcontract has more than 2,500 address holders, otherwise you will be rejected
- [ ]  Fork the Github repository
- [ ]  Create folder with name of token smartcontact address in checksum format blockchains/ethereum/assets/<token_smartcontract_address>/.
- [ ]  Tell your designer that token image must be in PNG format, avoid transparent background, recommended size 256x256px, max. 512x512px, with max file size of 100kB, for further details read image rules.
- [ ]  Upload your logo with file named logo.png to previously created folder with smartcontract address, and if you done all correctly your path should look like this. blockchains/ethereum/assets/0x1234567461d3f8Db7496581774Bd869C83D51c93/logo.png
- [ ]  Create info.json file with info about the token/project
- [ ]  Create a pull request to the main repo
- [ ]  Pay the processing fee

**Comment by DefiHunter** [comment]
@curateproject pls check when u have a moment

**Comment by curateproject** [comment]
Hi @pellarboss this all got done here:

https://github.com/curateproject/assets

I've also attached the folder below, can you check the code is correct?
[0xE1c7E30C42C24582888C758984f6e382096786bd.zip](https://github.com/pellartech/curate/files/6897034/0xE1c7E30C42C24582888C758984f6e382096786bd.zip)

**Comment by pellarboss** [comment]
@curateproject no the json file is incorrect

I've updated it, here is its contents

```
{
    "name": "Curate",
    "symbol": "XCUR",
    "type": "ERC20",
    "decimals": 8,
    "description": "-",
    "website": "https://curate.style/",
    "explorer": "https://etherscan.io/token/0xE1c7E30C42C24582888C758984f6e382096786bd",
    "status": "active",
    "id": "0xE1c7E30C42C24582888C758984f6e382096786bd",
  }
```

I suggest adding a description to this as well

for BEP20, you should create a Separate PR to add the token to the wallet

**Comment by madtocc** [comment]
description is optional. 
links are also optional but it does not hurt to add them 😅
I think just updating the json and creating the PR should work.
```
{
    "name": "Curate",
    "website": "https://curate.style",
    "description": "The Gasless NFT Marketplace",
    "explorer": "https://etherscan.io/token/0xE1c7E30C42C24582888C758984f6e382096786bd",
    "type": "ERC20",
    "symbol": "XCUR",
    "decimals": 8,
    "status": "active",
    "id": "0xE1c7E30C42C24582888C758984f6e382096786bd",
    "links": [
        {
            "name": "telegram",
            "url": "https://t.me/curate"
        },
        {
            "name": "instagram",
            "url": "https://www.instagram.com/curateproject"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/curateproject"
        },
        {
            "name": "reddit",
            "url": "https://www.reddit.com/r/XCUR"
        },
        {
            "name": "discord",
            "url": "https://discord.gg/mtBpcqtBaK"
        },
        {
            "name": "github",
            "url": "https://github.com/curate-project"
        }
    ]
}
```

**Comment by curateproject** [comment]
Description: The official token for Curate

@madtocc can you add the above description and submit the PR for us please

**Comment by madtocc** [comment]
PR submitted. https://github.com/trustwallet/assets/pull/12670

Need to pay the fee:
https://github.com/trustwallet/assets/pull/12670#issuecomment-896751142

Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.
💀 As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.
See also the PR Fee FAQ.

Please pay 2000 TWT with the memo 2670 to the address **bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098**.
Alternatively, 5 BNB is also accepted (same memo & address).

QR code: [Trust](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fcoin%3D714%26address%3Dbnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D2670) | o[ther wallet](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098%26amount%3D2000%26memo%3D2670)

Notes:

Trust Wallet Tokens (TWT) can be obtained through our Referral Program or from DEXs/exchanges.
New tokens without significant usage are rejected, see criteria mentioned above.
One PR should be for a single project; PR's with more than 10 logos will be rejected.
Payment evaluation happens automatically, but with a few minutes delay. When payment is detected, an Accept Review is automatically placed on the PR, which is a condition for merge.
Evaluating the PR is done manually, and it is merged only if all conditions are satisfied.
TWT-BEP2 is supported (Binance Chain), TWT-BEP20 version on Smart Chain is not.

**Comment by DefiHunter** [comment]
Fee paid - https://explorer.binance.org/tx/2CD57142D3DFD69271049E407E33135B659CE9F0C425232A4B30942253C55AE3
