### ISSUE TITLE
Default decsending 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#129]
Can we make the marketplace default sort by descending price instead of by latest please

**Comment by madtocc** [comment]
what is the idea? I guess if you have a lot of fields you shouldn't set others based on a particular field otherwise it will generate an unnecessary complex uses cases to handle and the user might not even notice the change... I haven't seen any filter that have multiple fields change the order of any other fields based on the selection. In my opinion this is not user friendly. 

e.g If I want ascending price and want to check out the other sort options and change to likes for instance when moving back to price it will be set to descending and user will have to change the order... some users won't understand and others will think it is a bug 😅

If you really want that, please describe how do you want to handle interaction with other fields as well.

**Comment by DefiHunter** [comment]
@curateproject

**Comment by DefiHunter** [comment]
I would presume that like how we can sort by verified, we add another option in the drop down for likes

Then users can chose ascending or descending

**Comment by curateproject** [comment]
Hi @madtocc we'd like to default the marketplace (not the homepage) by highest price (descending i.e from highest to bottom) - also can you update the minimum to 25 XCUR as the NFT listing price please
