### ISSUE TITLE
Show Curate preview logo

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#137]
Show the Curate logo when pasting app links i.e preview image when pasting the link in twitter

![Screenshot_20210725-171325_Twitter.jpg](https://user-images.githubusercontent.com/51517619/126905937-27288ab4-6c61-40e9-b25d-116463a55558.jpg)

**Comment by pellarboss** [comment]
@madtocc i presume:
- is it possible to add a favicon to the dynamic link
- if not possible, can we use our own URL?

**Comment by madtocc** [comment]
Will include the photo. @curateproject @DefiHunter, do you want to add the profile/product photo as a preview or the curate logo?

@pellarboss regarding the favicon, we can't change it, since it is a url generated under their domain thus have their favicon. 
Yes, we can setup any (owned) domain.

**Comment by DefiHunter** [comment]
I rate we use the Profile/product photo as it feels more natural

**Comment by madtocc** [comment]
I will add the curate logo for now. Feel free to open a new issue to change it later. To include a photo we will need to meet some criteria since they should have at least 300x200 and a size < 300KB. Currently there are some photos that may have more than 300 KB and some also might have a smaller width or height I don't know since we don't have any limitations, which will cause them to not be shown.

**Comment by curateproject** [comment]
Ok that's fine for now @madtocc
