### ISSUE TITLE
App Constant Crash

### ISSUE THREAD

**Issue by toomingos** [pellartech/curate#145]
https://user-images.githubusercontent.com/86632157/127365149-45b14460-d737-48f0-8db2-a0f156dfffb2.mp4
This user is having trouble with the app that keeps on crashing while scrolling down the marketplace

**Comment by madtocc** [comment]
I’m not able to reproduce on Android. But I did profile the memory and it is probably a memory issue. So app crashes due out of memory. We are using the “source” you guys provided to handle the staggered grid, i.e. tu support different heights for each image. I warned about the performance issue that it causes and apparently it also leaks memory.
Bear in mind this is not an easy fix since it is an issue on how this specific library renders the images and clears memory, so my recommendation is have a fixed height/width for each image the same we do for the featured section and use the official Flutter's grid view for that matter.

**Comment by curateproject** [comment]
Hi @madtocc if we have a fixed height/width for each image will this only affect the NFT marketplace?

**Comment by madtocc** [comment]
Apparently the only issue is when we load couple hundred of products. So  I guess we could just replace the marketplace grid. But ideally we should replace all the grids in the app so they look alike. The product detail don't need to be change so it can still have its dynamic height.

**Comment by curateproject** [comment]
Can you send a screenshot or video preview of how this will look?

**Comment by madtocc** [comment]
We are working in a work around maybe it won't need to change them.
