### ISSUE TITLE
Referral page + username tweaks 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#149]
Can you give the referral section it's own page and remove it from the edit page section.

Can you then add a link to the referral page on the app menu 'Referral' 

Referral page:
1. Add share icon which copies to clipboard the app download URL with the referral code added
2. Username section should be on the edit details page (ability to view/edit)
3. Usernames should also show on the profile page
4. Usernames should be searchable on the marketplace (just how display names work when searching for them)
5. Usernames should show on the profile share URL so it's easier for users to know their own profile URL

Can you also add the tiered referral breakdown from issue 136

**Comment by madtocc** [comment]
@curateproject yes, can remove and create a section however I guess we could show under your profile like below. Instead of the following button we add the referral code:
![image](https://user-images.githubusercontent.com/12486417/127690460-d867c3ba-79f1-4ff9-b6ca-f80dd24ec661.png)

let me know if this is ok or you'd rather have a dedicated menu entry.

Upon clock it generates a link to the app and also embedded the user referral, which can autocomplete when the user joins using this link. We still have to implement this feature, but it will be there.

regarding the username we have to implement it on the server-side first.

**Comment by curateproject** [comment]
Can we have both @madtocc ?

**Comment by madtocc** [comment]
sure
