### ISSUE TITLE
Stats and Metrics -  NFTs

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#160]
Properties:
Contract Address
Token ID
Blockchain (i.e. ETH, Matic)
Royalties
NFT properties (Name, Type, % of ownership)
Collection attachment (i.e. being  able to stay at the OpenSea collection)

Explanation : The ability to import existing data on the blockchain for imported NFTs , i.e to pull the history of the NFT on other blockchains into the Curate app 
- Allow users to import previous royalty 
- View contract address (Orignal) 
- Name of collection its from - if notable maybe we can do a verified check - Like cryptopunks for example to verify an original cryptopunks 

Stats and Metrics:
Collection - which collection its from 
Number of Items - # of items in collection and specific item #
Number of Owners - Current and previous owners address or name if possible 
Floor Price - Min sale price of the collection 
Volume Traded of the collection 
    
NFT
Price History - Historical price cross platform - pull sales history from blockchain using NFT address
Event (Sale, Transfer, Bid, Bid Cancel) - Can pull using NFT address 
Owners - should be available on NFT address 
Date of Transfer/Sale - On Etherscan too 
Creator - original creator of the NFT 

Pulling the above data for an imported NFT 

Roy - Happy to run through this with you and figure out the best way to do each task

**Comment by DefiHunter** [comment]
Allow Users to import existing Royalties - I have an idea for this @pellarboss for how it could work - Happy to jump on a call to hash it out

**Comment by DefiHunter** [comment]
Initially we can start with existing NFTs on the platform

**Comment by toomingos** [comment]
Stats and Metrics:

We should have dedicated pages for each NFTs product, user, and Collection where a user can check the stats and metrics. The way we can integrate this easily without cluttering the app is having a button on the NFT product page, the user page, and the collection page, that takes the user to a stats page. For each category, I have gathered the stats and metrics that I see fit.

Collection: Same as in #236
Number of Items- Number of Non-fungible tokens pegged to a smart contract
Number of Owners
Floor Price- Token ID with the lowest listed price
Volume Traded of the collection
CMC
Trending Score- 0.3*(Number of Sales in 24hrs)+ 0.2*(Number of likes in 24hrs)+ 0.175*(Number of views in 24hrs)+ 0.175*(New Followers in the last 24hrs)+ 0.05*(verified badge boost)+ 0.1*(Featured product boost)

NFT Product:
Price History - Historical price history
Events (Sale, Transfer, Bid, Bid Cancel) - Should look like the price history table we currently have, but we need to show these events, as they register in the XCHAIN

User Page:
Number of Items Sold
Number of Collectors- Number of different users that bought the User's NFT products
Volume Traded of his created NFTs
Trending Score- 0.3*(Number of Sales in 24hrs)+ 0.2*(Number of likes in 24hrs)+ 0.175*(Number of views in 24hrs)+ 0.175*(New Followers in the last 24hrs)+ 0.05*(verified badge boost)+ 0.1*(Featured product boost)

**Comment by toomingos** [comment]
**Update** Smart Contracts

-Add smart contracts to the marketplace, this way we can peg each NFT to a designated Collection. Each NFT has a token ID number. 

-We need to host smart contracts from NFTs that are imported, that are minted on our app whether manually (on the easy minting page) or created through the smart contract (on the advanced minting page)

Basic minting Smart Contract:

For our auto generated smart contracts we only need to create a basic smart contract with the token ID numbers and all the rest of the metadata we’re currently collecting from creators.


I.e.

NFT Name: Penguin #47

This NFT is connected to the collection by the smart contract address to it, he’s token ID would be 47, in order to identify it out of all of the other NFTs in the collection.

Minting Collections

-The minting page should have a box where the user picks whether he wants to mint a 1/1 (one of one, a unique piece that’s not related to others) or a collection. If the user selects the collection option he should be able to select his current collections or create a new one. So, every time a user creates a new collection, there should be a smart contract address assigned to it, in the back end. 

-Users can add/mint new NFTs to collections created in the past

-We should create a new advanced mode into the Mint NFT page, where more savvy users can create smart contract driven collections. Since we want to keep the easy minting moto, we need to keep this advanced mode easy.

Advanced minting Form Structure:

-Name of Collection

-Collection Description (shows up on the collection page)

-Rollout type:
Private: After the collection is Batch minted the users have to buy and get the NFT with the next Token ID number. So if a collection already sold 35 NFTs, the next user who purchases the collection NFT would get NFT #36. This mirrors the MInt-to-buy rollout on other platforms, primary market buyers are assigned an NFT with random properties.
Public: After the collection is Batch minted all of the Collections items are available in the marketplace and users can pick the NFT they want to buy right away

-Fixed Price/Auction with a minimum bid

-Collection’s Smart Contract: 
Paste and Auto Detect the rest of Collection’s features/specs:
-Number items (token IDs)
-Properties of each on (metadata)
-Royalties

**Comment by toomingos** [comment]
Updated Rankings Page

-There should be a “Stats” page, where users can check the top collections and sellers. Where the user can filter and pick the criteria of the rankings. SUGGESTION: Place it on top of the NFT marketplace bar, next to the “Home” and “Marketplace” options.

Criteria for Collections:

Users can select between these time windows for rankings: All time, Last Month, last week, last day (24hrs) - Slider bar - Horizontal

![image](https://user-images.githubusercontent.com/86632157/134321733-c9ec630b-9e2c-4bce-be4d-59ee7876b7de.png)

Ranking: Fixed Number list, always representing the order of the Criteria selected.

Total Volume: Sum of value of all transactions of the items.

Market price- Average of last 5 products solds

Floor Price: Minimum price available in market for the collection

Trending Collections Algorithm: 0.3*(Number of Sales in 24hrs)+ 0.2*(Number of likes in 24hrs)+ 0.175*(Number of views in 24hrs)+ 0.175*(New Followers in the last 24hrs)+ 0.05*(verified badge boost)+ 0.1*(Featured product boost).

Stats and Metrics Dedicated Page (Creators, Collections, NFT)

We should have dedicated pages for each NFTs product, user, and Collection where a user can check the stats and metrics. The way we can integrate this easily without cluttering the app is by having a button on the NFT product page, the user page, and the collection page, that takes the user to a stats page. For each category, I have gathered the stats and metrics that I see fit.

Smart contracts on the app need to be linked to their etherscan page.

Collection: Same as in #236
Number of Items- Number of Non-fungible tokens pegged to a smart contract (Collection front page & dedicated metrics page)
Trending Score- 0.3*(Number of Sales in 24hrs)+ 0.2*(Number of likes in 24hrs)+ 0.175*(Number of views in 24hrs)+ 0.175*(New Followers in the last 24hrs)+ 0.05*(verified badge boost)+ 0.1*(Featured product boost) (Collection front page & dedicated metrics page)
Number of Owners (Collection front page & dedicated metrics page)
Floor Price- Token ID with the lowest listed price (Collection front page & dedicated metrics page)
Metrics on the dedicated metrics page:
Volume Traded of the collection
Market Price
10th Percentile Price/Median Price/90th Percentile Price
Graph Section; User picks Historical data from the following options, and timeframe (days, weeks and months)
-NFT solds: counts the number of NFTs sold on the selected timeframe
-Volume through time: accounts for value in XCUR transaction on selected timeframe
-Price Average: Accounts for the average price of that day/week/month, depending on the selected timeframe.
-Floor Price: minimum price over time.
Top 10 Selling NFTs of the collection: the 10 NFTs out of the same collection that have sold for the highest prices. (We could allow the user to keep scrolling down, making it just the top selling NFTs)

![image](https://user-images.githubusercontent.com/86632157/134321780-39957093-f0a1-45e4-86d5-a4cae980fc4b.png)

Rarity Score Ranking:
The rarity of the NFT is determined by how rare the elements of the NFT in question are. As an example let’s take a look at an NFT on Rarity. tools. This NFT has the highest score of the collection since elements like the Zombie Rest and the Zombie Fog are only present in this NFT, on another hand, the Personality is unpunctual, something that 394 NFTs have in the collection.

![image](https://user-images.githubusercontent.com/86632157/134321805-9f9e1300-98ee-4cb5-9fc7-8061c6947b22.png)

We should have a Rarity Score filter that ranks the collections NFTs on the rarity of the elements that the smart contracts designates to each of the collections NFTS.

NFT Product:
Price History - Historical price history
Events (Sale, Transfer, Bid, Bid Cancel) - Should look like the price history table we currently have, but we need to show these events, as they register in the XCHAIN
Properties
Rarity Score Ranking

User Page:
Number of Items Sold
Number of Collectors- Number of different users that bought the User's NFT products
Volume Traded of his created NFTs
Trending Score- 0.3*(Number of Sales in 24hrs)+ 0.2*(Number of likes in 24hrs)+ 0.175*(Number of views in 24hrs)+ 0.175*(New Followers in the last 24hrs)+ 0.05*(verified badge boost)+ 0.1*(Featured product boost)

**Comment by toomingos** [comment]
https://www.figma.com/file/7K8McIi4ZqToPLn2f1pLEF/Curate-v4 Here's the figma link

**Comment by TheOneXi** [comment]
@pellarboss and @madtocc above is the figma link to use for the new stats and metrics page

**Comment by pellarboss** [comment]
lets close this issue and recreate a new ones - cleaner that way

linked to #463
