### ISSUE TITLE
Enable ETH and USDXC for Payments (Not DOT for now)

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#175]
User sets listing Price in USD 

When Paying for an NFT 

If Paid in XCUR - 4% Fee and 1% Rebate as designed 

If chose to pay in ETH 
- 7% Commission and no rebate

**Comment by DefiHunter** [comment]
Open for discussion

**Comment by curateproject** [comment]
To confirm @pellarboss 

When minting, the seller sets the price in USD

When the buyer pays, if paid in XCUR, the current set up applies (4% commission and current rebate)

If ETH option is selected by buyer, than 7% commission taken and no rebate.

**Comment by DefiHunter** [comment]
Yes this would be great please @roy

**Comment by pellarboss** [comment]
V4 scope is set, we can tackle this after v4, you guys can determine priorities for the next release

USDXC will work - since its on xchain

but DOT, ETH will not work

ETH has a transfer cost per send, meaning, most of the time, the 0.5%, 4% sends will not succeed since transfer fees will exceed actual payout amount

DOT will not work as well, the transfer costs are high, and there is a need for a minimum 1 DOT per account

**Comment by DefiHunter** [comment]
Would wrapping  the funds like XCUR solve this ?
