### ISSUE TITLE
Change share URL to take you to app on desktop/browser

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#249]
Can you update the share URL so that the URL takes users to the web app if they don't have the app installed?

Currently if you don't have the app installed, the URLs only take them to curate.style

Would like the URL to link to the exact page in question i.e profile, NFT etc on the web app

**Comment by madtocc** [comment]
Unfortunately, currently it is not possible. Since we use firebase dynamic links for that and it is not available for web. What we can do is add deep linking in the web which is typing the address like: https://app.curate.style/?product=6f69841ae6a3f8d694bca1d0/?product=6f69841ae6a3f8d694bca1d0 and the web redirects to that page. This is what the Firebase plugin does on the Mobile, but we can add support to that with deep links in the routing... This, however, needs to re route the whole app (which is kind of laborious) and we are aiming to do this with the new UI update.
My suggestion is to defer to sprint with the UI update
