### ISSUE TITLE
SOL Integration - Phase 1

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#320]
Integrate SOL token and blockchain 

Phase 1
Deposits and Withdrawls on X blockchain for supported Tokens within the Curate app
X Token integration for Deposits and withdrawls

**Comment by toomingos** [comment]
For the Solana integration, we should prioritize the following steps, not too technical so I'm not sure if one is a precursor of another. But since we're partnering with NFT gaming projects we need to facilitate the following first:

-Import, Custodial, and Export of $SOL NFTs

-Mint

-Token Integration

-Phantom wallet integration.

**Comment by pellarboss** [comment]
For stage one, we are doing:
- Deposit / Withdraw SOL - like DOT
- Buy XCUR with SOL - like DOT
