### ISSUE TITLE
Guest view for the app

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#377]
Ability for guests to view app without having to signup/login 1st

**Comment by pellarboss** [comment]
proposed workflow changes

first time user, show marketplace, ability to filter etc
go in to product detail, instead of buy, show "Please Register or Sign In to continue" 
the (+) button in marketplace, link to Login Page (but can back in to previous page, pop and push)

go to account, my nfts, settings (the other 3 icons at the bottom0, show "Please Register or Sign In to continue"

**Comment by curateproject** [comment]
Yes please just like that
