### ISSUE TITLE
[APP] UI Changes

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#41]
Ability to swipe back on pages like most apps (see attached heat map) 
![image](https://user-images.githubusercontent.com/72095738/123400757-61fa1980-d5a6-11eb-8c66-54478f859444.jpeg)

Below images 
![image](https://user-images.githubusercontent.com/72095738/123400800-6e7e7200-d5a6-11eb-9f09-958371aebc83.jpeg)
![image](https://user-images.githubusercontent.com/72095738/123400810-70e0cc00-d5a6-11eb-8dba-f7f6058d7a63.jpeg)
![image](https://user-images.githubusercontent.com/72095738/123400820-73dbbc80-d5a6-11eb-828c-8841eccdea7b.jpeg)
![image](https://user-images.githubusercontent.com/72095738/123400830-763e1680-d5a6-11eb-82f1-52fffc3ff530.jpeg)
![image](https://user-images.githubusercontent.com/72095738/123400849-79390700-d5a6-11eb-9b08-47b1fe9e6bcf.jpeg)
![image](https://user-images.githubusercontent.com/72095738/123400857-7c33f780-d5a6-11eb-959b-355b9c4cef17.jpeg)

The home button on the iPhone is not taken into account, the content is drawn before it. Then it disappears and breaks off. This must be taken into account since November 2017, when the 10 iPhone was released.

![image](https://user-images.githubusercontent.com/72095738/123400933-92da4e80-d5a6-11eb-9edc-4516648d491b.jpeg)
![image](https://user-images.githubusercontent.com/72095738/123400945-95d53f00-d5a6-11eb-88bd-39016e79bc4d.jpeg)

**Comment by curateproject** [comment]
+ option to choose 2 columns or 3 (default) for the maketplace listing page

**Comment by madtocc** [comment]
Some stuffs are a little bit confusing:
1 - ![image](https://user-images.githubusercontent.com/12486417/124601266-051c2000-de3e-11eb-9690-dd8adc64fd5c.png)
1 - Here we have an app bar which hides when the user scrolls, since there's no app bar it shouldn't have an elevation, as far as I know. You can see the same behavior in apps like gmail. If you want to add an elevation let me know, or what you want it is not clear to me.

2 - ![image](https://user-images.githubusercontent.com/12486417/124601836-ac00bc00-de3e-11eb-94ca-2d3d5c4c50a6.png)
2 - do you want to make this rounded as well? apart from that and the submit button, all the border radius are the same now.

3 - here do you want to remove the horizontal padding? 
3 -![image](https://user-images.githubusercontent.com/12486417/124602064-dd798780-de3e-11eb-8e21-88c6f3b28cc5.png)
