### ISSUE TITLE
Add 'Gaming' section on Featured NFT page

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#441]
Add new tags for collections
- gaming
- metaverses
- pfps
- membership

Add sub-menu on NFT featured section with the following categories to choose from (including verified sellers)

**Comment by madtocc** [comment]
This issue is not clear to me.
> Add new tags for collections
> 
> * gaming
> * metaverses
> * pfps
> * membership
> 
We currently don't have tags for collections, only for NFTs. Is this for collections or the NFTs? If it is for NFT, you can add them to the Admin panel. If it is a tag for a collection, it needs to be created since it does not exist (if so, what happens to the existing collections?).


> Add sub-menu on NFT featured section with the following categories to choose from (including verified sellers)

How do you exactly want to display this? A tab bar below the tab bar with those options or what exactly?

**Comment by TheOneXi** [comment]
Just need to create new tags for NFTs (not collections) so apologies.

Where in admin can I create/manage the tags?

Can you add a tab bar below the tab bar and show me a preview here of how it'll look?

I think we'll need to increase the amount of NFTs featured on the featured page to 12 and also 12 for all sub featured categories

**Comment by madtocc** [comment]
> Where in admin can I create/manage the tags?
> 
https://admin.curate.style/settings
![image](https://user-images.githubusercontent.com/12486417/154289143-79b2a46f-b583-474b-a980-25d15c90d9b8.png)

> Can you add a tab bar below the tab bar and show me a preview here of how it'll look?
> 
I don't think it will look cool, but it is up to you and honestly, I have never seen two tab bars stacked. I'd add a similar to what we had before... If you want to add several sections to featured I think it would be better to display them like this:
Featured
scrollable horizontal list
Gaming
scrollable horizontal list
.
.
.

> I think we'll need to increase the amount of NFTs featured on the featured page to 12 and also 12 for all sub featured categories

Even increased to 20

Also if you want to feature for a specific tag it will have to somehow Feature as N options, since an NFT can have multiple tags. So instead of having the "Feature" button, you will need to have multiple feature buttons or a Feature as and you pick the option.

**Comment by TheOneXi** [comment]
Thanks for the update I'll come back to you on these points for now let's move forward
