### ISSUE TITLE
Allow creators to Edit Collections & NFT's 

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#513]
### COLLECTIONS
Allow creators to edit collections:

1. Change collection description
2. Change collection banner
3. Change collection photo
4. Delete Collection (when there is no NFT minted within the collection)
![allow edit collections](https://user-images.githubusercontent.com/93180831/158012739-4dd21b3d-2931-4b1e-864a-48f074778ec1.jpg)

### NFT's

Allow creators to edit NFTs':
1. Description
2. Name
3. Price
4. Increase the allowed title length to 40 characters

**_NOTE: Only allow NFT edit for creators to edit NFTs that are minted but unsold._**

**Comment by madtocc** [comment]
regarding the NFT edits, it is not that simple since it can lead to some problems.
A product title edit and name edit could lead to something being approved or not? if so you need to reset the NFT to pending status, correct?

For example, I make an offer to a product: 
name: Da Vinci art
description: Leonardo da Vinci's original art.

user can receive an offer and before accepting it, he can change it to
name: shitty Art
description: who even buy this?
And accept the offer. The product sold will have the last description.

In my opinion, it should either cancel all the offers when doing so or reset the product to pending status and it should be reviewed again by the team and approved.

**Comment by Catherineanne91** [comment]
@madtocc  Can you please allow EDITS on NFT's ONLY if there are no offer on the product, instead of resetting to pending
