### ISSUE TITLE
[APP] Watermarking

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#58]
Watermarks on NFTs in the public marketplace, but full quality picture without watermark for the owner.

**Comment by pellarboss** [comment]
Please confirm if you would like to do this, my comments:
> I think you should check if artists & buyers like that, because image is the product
> I would be unhappy if my iphone or shoes came with a watermark from the retailer

**Comment by DefiHunter** [comment]
Could we make it such that the watermark is not embedded into the NFT but rather a front-end tweak for the NFT marketplace ? 

If the Original NFT is not tainted I think it would be fine , We could allow artists to toggle this when minting . Possibly could have a "tamperproof" slider that could be enabled or disabled so that the artist can decide how to proceed

**Comment by DefiHunter** [comment]
Thoughts ?

**Comment by DefiHunter** [comment]
Prevents users from screenshooting NFTs in app if they not the owner. Or at least their screenshot wont be 100% quality

**Comment by curateproject** [comment]
Could disable screenshots on the app but this will prevent a lot of feedback issues so let's not disable screenshots everywhere

**Comment by pellarboss** [comment]
confirmed, implementation:

Watermark = a translucent © in the lower right of the main picture in app item detail screen apart from My Collection

**Comment by curateproject** [comment]
Great, can we see an example @pellarboss

**Comment by madtocc** [comment]
how do you want to handle the zoom? since user can move and zoom in and zoom out he can "hide" (crop) the watermark.

1. can't zoom NFTs that he does not own
2. watermark on the whole screen
3. another idea

**Comment by DefiHunter** [comment]
Place the watermark "c" in the middle of the screen, we can play with transparency until it reaches a sweet spot

Or Diagonally place the curate full name across the screen

**Comment by madtocc** [comment]
Guys, I've being testing this feature and I don't know if it is really useful as its current state.

If the image is centered and we add a centered watermark logo the user can simply take a screenshoot and move to any direction and copy/past the part without the logo. it doesn't matter if it cover the screen diagonally or not.. if it is zoomed it can be reconstructed easily....
e.g
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-19 at 15 24 11](https://user-images.githubusercontent.com/12486417/126208894-939d515c-6b77-43d0-a5a6-86cc6fa22b95.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-19 at 15 24 15](https://user-images.githubusercontent.com/12486417/126208901-963b8f95-f5d7-4e4b-9c26-6bcd27eea854.png)

Since the watermark has an opacity the white white pictures won't show it properly.. we can add some kind of blend so it shows a different color but I don't know if it will change the visual in a negative way. Please take a look and let me know if I should disable for now.

**Comment by DefiHunter** [comment]
@madtocc  try adding a bit more grey to the color and increasing the size by 75%

**Comment by DefiHunter** [comment]
@madtocc  lets use the one you have for now, its good for now
