### ISSUE TITLE
Users commission/tier stuck on base

### ISSUE THREAD

**Issue by TheOneXi** [pellartech/curate#580]
App user email: falezler2013@hotmail.com
Device: iOS
App version: v7.1

This user has 55 XCUR (not staked) but just in his balance yet it still shows he is on base tier with 5% commission, instead he should be on standard tier.

Can you help? Thanks

![Image 2](https://user-images.githubusercontent.com/51517619/163216389-47bdc61d-4bb7-464f-9077-80d5ff75e02e.jpg)
![Image 1](https://user-images.githubusercontent.com/51517619/163216400-67577cc9-aa3d-441e-8da7-d5c74c3ab5f6.jpg)

**Comment by madtocc** [comment]
To me it's correct
Base tier = no staking = 5% commission
Standard tier = 20 XCUR staked = 4% commission.

**Comment by TheOneXi** [comment]
Many thanks.

Can you change the front end to display 5% as 4% so it's simple for our users to understand

**Comment by madtocc** [comment]
You need to update the default transaction fee, James.
Currently if user sells something for 100 XCUR he will receive
100
-5% 
+0.5% rebate
He will receive 95.5

Buyer will spend 100
But will receive 0.5, so hee will spend 99.5

If you want to change to everyone that don't have a stake to 4 you need to update the fee in the admin panel, otherwise it will show 5, since the transaction fee is 5

**Comment by eventang2015** [comment]
updated response , but the real  commisiion fee is  5%.

**Comment by eventang2015** [comment]
no stake - 5% 
staked 20+ 4%
<img width="2027" alt="156890642-2d0d0c36-ef32-4e42-bd06-8cb2b1651202" src="https://user-images.githubusercontent.com/28645146/163759320-22d05e8f-b6bd-4ba6-85cb-b78e75bdaa83.png">
