### ISSUE TITLE
User's NFT (MP4 File) Cannot be Viewed on the App

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#591]
User:  nesteggsnft@gmail.com
https://admin.curate.style/users/c166730e94d6e8784844873a154e45172668
Issue: User's NFT (MP4 File) Cannot be Viewed on the App

NFT: https://admin.curate.style/product/049d5657b5dff87553a127b4/detail

When searched in app, the preview of the NFT shows :

![278325768_300863648860444_150706687138120281_n](https://user-images.githubusercontent.com/93180831/163940561-ded71a15-97f2-4aa4-b853-105e96f21278.jpg)

When the NFT is clicked, it only shows the curate logo. Can't view the NFT

![278243610_410551870909294_8508375807381996078_n](https://user-images.githubusercontent.com/93180831/163940581-9d4c8f1f-73d2-484d-97a7-1be86b63a651.jpg)

Tried: Clear Cache
OS: Android v7.1.2b154

**Comment by madtocc** [comment]
It is a video... In order to display the video, you have to download it.
A video won't show up instantly. The amount of time it will take to show depends on the size of the video and the network speed.
I am able to see here without any problems for both iOS and Android.

![Screenshot_1650900543](https://user-images.githubusercontent.com/12486417/165122062-552cf243-ef92-4ab7-8a56-6eda1909917b.png)
![image](https://user-images.githubusercontent.com/12486417/165122205-885509ae-1eb8-4546-be55-0bb9d0586e69.png)

**Comment by Catherineanne91** [comment]
got you thanks
