### ISSUE TITLE
[App] Bug on iOS - KYC

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#68]
For KYC page at some point, the buttons stop responding, nothing happens when I click on "upload photo". Also at this moment, if the field had an error, it does not disappear, even if I enter the correct text.
Now I wanted to record a video - but everything went well. But before that, there was an error 2 times, I think some users will also have it.

**Comment by pellarboss** [comment]
Marco, please investigatie

**Comment by madtocc** [comment]
I was able to reproduce, however I was not able to identify the problem in the first attempt... since it takes some time trigger I decided to refactor the KYC and I took the opportunity to update the UI (added the same we used in the NFT listing) i.e removed the photo picker button and added the photo preview. 
While testing the app in a iOS physical device the lock screen showed all the times after picking the photo... do you guys @pellarboss @DefiHunter  experience this on iOS? I was not experiencing this behavior on Android. I have applied a fix for that as well.
