### ISSUE TITLE
Allow users to search profiles 

### ISSUE THREAD

**Issue by curateproject** [pellartech/curate#72]
Profile discovery:

1. Allow users to search profiles via name search on the 'my profile' page i.e search bar, verified users get sent to the top if keywords match

2. Allow anyone to view followers i.e click followers and see a list of followers (sorted by most recent)

3. Allow users to adjust/crop their profile image as some are getting stretched.

**Comment by madtocc** [comment]
I guess we have to rethink about this.
Under My profile should show only your profile. I don't think it is intuitive to search for users under your profile. We maybe should have a menu entry or have an option to search for profiles on the marketplace filter. Let me know what you think @curateproject 

regarding the image stretched I guess it is solved, can you give me example of users that have the image stretched? 
We can add a feature to edit photos and show the preview. It would also be good to include under the mint as well. Let me know so we can create a new issue for that

**Comment by curateproject** [comment]
Yes @madtocc @DefiHunter a menu entry for search as well as adding usernames as a query that can be searched on the marketplace search will feel most natural.

@madtocc can you enable a crop image function for profile image uploads and NFT image uploads?

**Comment by madtocc** [comment]
Not for today but for the future:
My personal opinion
Home page should show the trending discovery etc and instead of Marketplace show the Nfts of the users you follow.
Menu entry Discovery we can have one view (which changes based on the filter for nft or users) or a tab view which shows nfts and users.
under discovery show the Marketplace/users

**Comment by curateproject** [comment]
The only issue is when you first join you are following no one and until we're in the tens of thousands of users it might be too early for that.

**Comment by madtocc** [comment]
yes, it makes sense... we could add something to redirect to discovery or show some random products if he does not have any followers. it was just a thought and I meant for the future. Currently we are not doing anything with users you follow...

Regarding the image edit, it will take some time to setup and test and since there are still some pending things for the today release I guess it will have to be pushed for later this week. I will let you know. 

So what do I do for user discovery? @DefiHunter @curateproject

**Comment by curateproject** [comment]
@madtocc can we have a drop down option on the marketplace search bar allowing you to search profile usernames there? The results will then show profiles below who match the keywords entered by name or username
