### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by DefiHunter** [pellartech/curate#79]
Add-Ons
Metamask,Trustwallet and Coinbase wallet  Connectivity 
Ability to Deposit ETH/XCUR by connecting your metamask 

- Users can connect their wallets provider to seamlessly deposit funds into the Curate NFT wallet 

Ability to Import NFTs by connecting Metamask

Users can seamlessly import NFTs 

Lets discuss

**Comment by DefiHunter** [comment]
https://www.binance.com/en/nft

We could go for a similar layout, I like the top pics, trending and featured

**Comment by curateproject** [comment]
If we're able to enable BEP20 XCUR deposits as well via Multichain wallets such as trustwallet

**Comment by toomingos** [comment]
This is something a lot of people find weird at first in a lot of the meetings I have. Usually, they assume it's desktop, not a big issue, I always manage to turn the convo around, But yes, down the road (because I understand we're spread thin) this would be great, expands user experience, and gives us bigger integration opportunities with metamask for example, which would break down the barrier of migrating to Curate as a collector/seller, This would also come in hand with the import of products from marketplaces that operate in desktop, and would make the process less tedious. 

Not an immediate priority, but an inevitable one, what do you guys think? @curateproject @DefiHunter

Would a simple frontend interface connected with API Keys work? How hard is a metamask integration feature?

**Comment by DefiHunter** [comment]
I agree @toomingos , I think a web app would break down the barrier for sure 

API is something we could work on, Is that correct @pellarboss ?

**Comment by curateproject** [comment]
For the desktop version can you display the following for the NFTs:

**Properties:**
Contract Address
Token ID
Blockchain (i.e. ETH, Matic)
Royalties
NFT properties (Name, Type, % of ownership)
Collection attachment (i.e. being  able to stay at the OpenSea collection)

**Stats and Metrics:**
Collection
Number of Items
Number of Owners
Floor Price
Volume Traded

**NFT**
Price History
Event (Sale, Transfer, Bid, Bid Cancel)
Owners
Date of Transfer/Sale
Creator

**Comment by pellarboss** [comment]
For V2, desktop is a web render of the mobile app, in the future we can extend the functionality (or rebuild web entirely)
